const r = require('express').Router();
const c = require('../controllers/aiController');
const { protect } = require('../middleware/auth');
const rateLimit = require('express-rate-limit');
const lim = rateLimit({ windowMs: 60000, max: 20, message: { success: false, message: 'AI rate limit exceeded' } });
r.use(protect);
r.post('/chat', lim, c.chat);
r.post('/cover-letter', lim, c.generateCoverLetter);
r.post('/interview-prep', lim, c.interviewPrep);
r.post('/skill-gap', lim, c.skillGap);
module.exports = r;
