const r = require('express').Router();
const c = require('../controllers/applicationController');
const { protect } = require('../middleware/auth');
r.use(protect);
r.get('/stats', c.getStats);
r.get('/', c.getAll);
r.post('/', c.create);
r.get('/:id', c.getById);
r.put('/:id/status', c.updateStatus);
r.delete('/:id', c.remove);
r.post('/:id/follow-up', c.followUp);
module.exports = r;
