const r = require('express').Router();
const c = require('../controllers/platformController');
const { protect } = require('../middleware/auth');
r.use(protect);
r.get('/', c.getAll);
r.post('/connect', c.connect);
r.delete('/:platform', c.disconnect);
r.put('/:platform/pause', c.pause);
r.put('/:platform/resume', c.resume);
r.post('/:platform/verify', c.verify);
module.exports = r;
