const r = require('express').Router();
const c = require('../controllers/profileController');
const { protect } = require('../middleware/auth');
r.use(protect);
r.get('/', c.getProfile);
r.put('/', c.updateProfile);
r.put('/preferences', c.updatePreferences);
r.get('/strength', c.getStrength);
r.post('/skills', c.addSkill);
r.delete('/skills/:category/:skill', c.removeSkill);
module.exports = r;
